---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "api.fullname" . }}-acc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "api.fullname" . }}-acc
rules:
  - apiGroups:
      - veverse.com
    resources:
      - gameservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - endpoints
      - events
      - configmaps
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "get"
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "api.fullname" . }}-acc
subjects:
  - kind: ServiceAccount
    name: {{ template "api.fullname" . }}-acc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "api.fullname" . }}-acc
